#include"comcanonicalmediascanner2.h"

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p comcanonicalmediascanner2.h -c ComCanonicalMediascanner2 mediascanner2.xml com.canonical.MediaScanner2
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

/*
 * Implementation of interface class ComCanonicalMediascanner2
 */

ComCanonicalMediascanner2::ComCanonicalMediascanner2(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComCanonicalMediascanner2::~ComCanonicalMediascanner2()
{
}
